### ISSUE TITLE
Band in cell location: show both

### ISSUE THREAD

**Issue by jidanni** [mroczis/netmonster-core#65] opened 2023-01-14 10:17 UTC
The "band in cell location" preference, we can pick 2100 or B1, but what if we want both? Perhaps add an additional choice to show both.

**Comment by Rekoo52anzi** [comment] 2023-01-24 11:13
> The "band in cell location" preference, we can pick 2100 or B1, but what if we want both? Perhaps add an additional choice to show both.

Duplicate of #

> [A]()

**Comment by mroczis** [comment] 2023-01-29 20:00
This is not related to NetMonster Core since such functionality is UI-related and only available NetMonster App. NetMonster Core does exposed both information if available. I'll consider adding such option into apps settings.

**Closed by mroczis** 2023-01-29 20:00 UTC

**Comment by jidanni** [comment] 2023-01-30 07:56
OK!

(Hmmm, all I can find other is https://github.com/mroczis/netmonster-web .
It seems there is no proper place to file NetMonster App issues.)
