### ISSUE TITLE
Misidentification of B66

### ISSUE THREAD

**Issue by Beat-YT** [mroczis/netmonster-core#58] opened 2022-12-13 15:25 UTC
So after the update now netmonster misidentify B66 as B3

![Screenshot_20221213-102133.jpg](https://user-images.githubusercontent.com/66485277/207373919-053cc098-2060-45dd-adab-c99aea015d52.jpg)

![Screenshot_20221213-102216.jpg](https://user-images.githubusercontent.com/66485277/207373896-c6e70ee5-55f8-4949-a86d-af93e23eea6d.jpg)

**Comment by mroczis** [comment] 2022-12-29 20:20
Duplicate of #59

**Closed by mroczis** 2022-12-29 20:20 UTC
